# Generated by Django 2.2.12 on 2020-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_info',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, default=19.9, max_digits=7),
        ),
    ]
