# Generated by Django 2.2.12 on 2020-10-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0002_indentinfo_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indentinfo',
            name='state',
        ),
    ]
