# Generated by Django 2.2.12 on 2020-10-24 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0005_auto_20201024_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentinfo',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 21, 40, 23, 795635), verbose_name='过期时间'),
        ),
    ]
