# Generated by Django 2.2.12 on 2020-10-25 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0007_auto_20201025_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indentinfo',
            name='info',
        ),
        migrations.AlterField(
            model_name='indentinfo',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 22, 31, 20, 908370), verbose_name='过期时间'),
        ),
    ]
