# Generated by Django 2.2.12 on 2020-10-26 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0008_auto_20201025_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentinfo',
            name='Inum',
            field=models.CharField(max_length=64, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='indentinfo',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 0, 20, 46, 303361), verbose_name='过期时间'),
        ),
    ]
