# Generated by Django 2.2.12 on 2020-10-26 00:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_city'),
        ('indent', '0009_auto_20201026_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentinfo',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 0, 23, 12, 210625), verbose_name='过期时间'),
        ),
        migrations.CreateModel(
            name='Indent_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inum', models.CharField(max_length=64, verbose_name='订单编号')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户')),
            ],
        ),
    ]
