# Generated by Django 2.2.12 on 2020-10-26 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0011_auto_20201026_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='indentinfo',
            name='info',
            field=models.TextField(default='', verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='indentinfo',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 19, 30, 42, 803121), verbose_name='过期时间'),
        ),
    ]
