# Generated by Django 2.2.12 on 2020-11-01 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0013_auto_20201101_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indentinfo',
            name='timeout',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 13, 20, 5, 454974), verbose_name='过期时间'),
        ),
    ]
