# Generated by Django 2.2.12 on 2020-10-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('detailed_address', models.TextField()),
                ('administrator', models.BooleanField()),
            ],
            options={
                'db_table': 'user_user_info',
            },
        ),
    ]
