# Generated by Django 2.2.12 on 2020-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201010_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='', max_length=32, verbose_name='地址select'),
        ),
    ]
