# Generated by Django 2.2.12 on 2020-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20201003_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='num',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
