# Generated by Django 2.2.12 on 2020-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20201101_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='imgurl',
            field=models.ImageField(default='http://127.0.0.1:8000/static/6.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='num',
            field=models.IntegerField(default=100, verbose_name='数量'),
        ),
    ]
